# Generated by Django 5.2.8 on 2026-01-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
