# Generated by Django 5.2.8 on 2026-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_is_active_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
