# # Generated by Django 5.2.8 on 2026-01-20 16:28

# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('hotel', '0004_hotel_age_hotel_citizenship_hotel_owner_contact_and_more'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Owner',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=255)),
#                 ('age', models.IntegerField(blank=True, null=True)),
#                 ('contact', models.CharField(blank=True, max_length=20, null=True)),
#                 ('email', models.EmailField(max_length=254, unique=True)),
#                 ('citizenship_number', models.CharField(blank=True, max_length=50, null=True)),
#                 ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#             ],
#         ),
#         migrations.AlterField(
#             model_name='hotel',
#             name='owner',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.owner'),
#         ),
#     ]




# Generated by Django 5.2.8 on 2026-01-20 16:28

import django.db.models.deletion
from django.db import migrations, models

def fix_owner_data(apps, schema_editor):
    Hotel = apps.get_model("hotel", "Hotel")
    Owner = apps.get_model("hotel", "Owner")
    try:
        # Ensure an Owner record exists
        owner, created = Owner.objects.get_or_create(
            name="Ravi Jung Basnet",
            defaults={"email": "ravi@example.com"}  #  adjust email if needed
        )
        # Update any Hotel rows that mistakenly stored the string in the owner column
        Hotel.objects.filter(owner="Ravi Jung Basnet").update(owner=owner.id)
    except Exception as e:
        # Fail silently if something unexpected happens
        print("Data fix skipped:", e)

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_age_hotel_citizenship_hotel_owner_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.owner'),
        ),
        # migrations.RunPython(fix_owner_data),  #  Added here
    ]