# Generated by Django 5.2.8 on 2026-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_owner_alter_hotel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
