# Generated by Django 5.2.8 on 2026-01-26 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_commissionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='registered_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('start_due_date', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.hotel')),
            ],
        ),
    ]
