# Generated by Django 5.2.8 on 2026-02-05 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_ownerstarrednotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_rooms', models.PositiveIntegerField(default=0)),
                ('deluxe_rooms', models.PositiveIntegerField(default=0)),
                ('suite_rooms', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.hotel')),
            ],
        ),
    ]
