# Generated by Django 5.2.8 on 2026-02-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_hotel_user_delete_roominventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_rooms', models.IntegerField(default=0)),
                ('deluxe_rooms', models.IntegerField(default=0)),
                ('suite_rooms', models.IntegerField(default=0)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deluxe_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suite_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotel.hotel')),
            ],
        ),
    ]
