# Generated by Django 5.2.8 on 2026-02-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_roominventory_roomprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendManagerAnnouncement',
            new_name='SendReceptionistAnnouncement',
        ),
    ]
