# Generated by Django 5.2.8 on 2026-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_rename_sendmanagerannouncement_sendreceptionistannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendAdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
