# Generated by Django 5.2.8 on 2026-02-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='hotel.hotel'),
        ),
    ]
