# Generated by Django 5.2.8 on 2026-02-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='hotel',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
    ]
