# Generated by Django 5.2.8 on 2026-02-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_commissionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendownerannouncement',
            name='hotel',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='owner_announcements', to='hotel.hotel'),
            preserve_default=False,
        ),
    ]
