# Generated by Django 5.2.8 on 2026-02-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_sendownerannouncement_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendadminannouncement',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_announcements', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='sendreceptionistannouncement',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_announcements', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='sendownerannouncement',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_announcements', to='hotel.hotel'),
        ),
    ]
