# Generated by Django 5.2.8 on 2026-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_sendadminannouncement_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
