# Generated by Django 5.2.8 on 2026-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='role',
            field=models.CharField(choices=[('Receptionist', 'Receptionist')], default='Receptionist', max_length=20),
        ),
    ]
