# Generated by Django 5.2.8 on 2026-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebookings',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managebookings',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
