# Generated by Django 5.2.8 on 2026-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_managebookings_checkin_managebookings_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='managebookings',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
