# Generated by Django 5.2.8 on 2026-03-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_managepayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managepayments',
            old_name='customername',
            new_name='name',
        ),
    ]
