# Generated by Django 5.2.8 on 2026-03-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_rename_customername_managepayments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='managepayments',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.managebookings'),
        ),
    ]
