# Generated by Django 5.2.8 on 2026-03-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_managepayments_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managepayments',
            name='booking',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.managebookings'),
            preserve_default=False,
        ),
    ]
