# Generated by Django 5.2.8 on 2026-04-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_alter_roomimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
