# Generated by Django 5.2.8 on 2026-04-12 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_hotel_latitude_hotel_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownerstarrednotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ownerstarrednotification',
            name='announcement_type',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='ownerstarrednotification',
            name='announcement',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ownerstarrednotification',
            unique_together={('user', 'announcement', 'announcement_type')},
        ),
    ]
