# Generated by Django 5.2.8 on 2026-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_guestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=4731),
        ),
        migrations.AddField(
            model_name='guest',
            name='loyalty_tier',
            field=models.CharField(default='Silver', max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='guest_profiles/'),
        ),
    ]
