import { Inter } from "next/font/google";
import "./style.css"; // your custom styles

//  Load Inter font with Next.js optimization
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Metadata for your app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//  Root layout wraps all pages
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
